/**
 * @file      hal_warmstart.c
 *
 * @brief     BSP Warmstart hook implementation for FPB-RA0E2
 *
 * The Clear BSD License
 * Copyright Semtech Corporation 2025. All rights reserved.
 *
 * This function is called at various points during the startup process.
 * It initializes the IOPORT driver with the configuration generated by e2studio.
 */

/*
 * -----------------------------------------------------------------------------
 * --- DEPENDENCIES ------------------------------------------------------------
 */

#include "hal_data.h"
#include "common_data.h"

/*
 * -----------------------------------------------------------------------------
 * --- PUBLIC FUNCTIONS DEFINITION ---------------------------------------------
 */

/**
 * @brief BSP Warm Start callback
 *
 * This function is called at various points during the startup process.
 * We use the BSP_WARM_START_POST_C event (after C runtime initialization)
 * to configure pins using the FSP IOPORT driver.
 *
 * @param[in]  event  Where in the startup process the code currently is
 */
void R_BSP_WarmStart( bsp_warm_start_event_t event )
{
    if( BSP_WARM_START_RESET == event )
    {
#if BSP_FEATURE_FLASH_LP_VERSION != 0
        /* Enable reading from data flash. */
        R_FACI_LP->DFLCTL = 1U;

        /* Would normally have to wait tDSTOP(6us) for data flash recovery.
         * Placing the enable here, before clock and C runtime initialization,
         * should negate the need for a delay since initialization typically takes > 6us. */
#endif
    }

    if( BSP_WARM_START_POST_C == event )
    {
        /* C runtime environment and system clocks are setup. */

        /* Configure pins using FSP IOPORT driver with generated configuration */
        R_IOPORT_Open( &IOPORT_CFG_CTRL, &IOPORT_CFG_NAME );
    }
}

/* --- EOF ------------------------------------------------------------------ */
